language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
script:
- sbt +test
- sbt clean coverage test coverageReport coverageAggregate codacyCoverage
env:
  global:
    secure: cH0ZmmNru4qbLQCkCn7nbgHoyvEg6jsxhdhLFcICaZnA+qp+U+RnYNq1kTIDVh0ehZOLcOUVvStU8dLWEFFmWwfsGwc51mT33hWEUUPInruInksjUm0S0ch41TgPRY9t1rYg8hMy5qpwlpHB1GnCmkoCyZ8vonO/qBb/wEBLJb/N75FRHk+v51lzI+iFZQKcv0P3ovvBW2GWUgU4YPx28/Tah5wL5Kw6PpH/pjjAg72KNvXFZJVexGyAfeY0b/XVqrDg7PCGz1eewxE8MHPzbV65rpUrNsF1/6Zvd7RilBUA6mqLsKJqAYaSC5fN43vG/U2eLcy/KjCM60e3U3hObAaN+Zw6chpXtWxeQpUaOxJxq1jBUGbeX3EsLGVuC3CPPEPDrfAJ4t5B+wXZQ7GROzYfjo5D03W2udfXY+e2Py8tPWPhy6MSUp4rXO0wfABobOvTk2gAZThi3SXus/gG9itAn4Sc4UDWVAtfoKnFXsYwPpjpuFsc7pr+Vj0wjPQ79H3D7wLPkbd4XKO7FpdmpPh6wHHm/5GhQNAi+LWgPC5lOiglDmvZWV+60/5T85QmcYjC5bO91LRI7UADeTGEmp13Mn/PF6QCNSUh8OqOtwRR85pOIIYDaelkihhNr5q21XyUE0/CLvpiTQm/59GVKzxc0pnnUUBUCjiCm0jRzaI=
