language: scala
scala:
- 2.11.12
jdk:
- openjdk8
script:
- sbt +test
- sbt clean coverage test coverageReport coverageAggregate codacyCoverage
env:
  global:
    CODACY_PROJECT_TOKEN=00980e4ba4894daf80ed6c3b4f56f9ae
